language: cpp

compiler:
  - gcc
  - clang

env:
  - TRAVIS_BUILD_TYPE=Debug
  - TRAVIS_BUILD_TYPE=Release

before_script:
  #Install ninja and the latest cmake to support ninja
  - sudo add-apt-repository -y ppa:kalakris/cmake
  - sudo apt-get update
  - sudo apt-get install cmake
  - cd .. 
  - git clone git://github.com/martine/ninja.git
  - cd ninja
  - ./bootstrap.py
  - cd ../ycm
  
  - cmake --version
  - mkdir build
  - cd build
  - cmake .. -DCMAKE_BUILD_TYPE=${TRAVIS_BUILD_TYPE} -DCMAKE_INSTALL_PREFIX=$(pwd)/../install
  - cd ..
  - mkdir build_ninja
  - cd build_ninja
  - cmake .. -GNinja -DCMAKE_BUILD_TYPE=${TRAVIS_BUILD_TYPE} -DCMAKE_INSTALL_PREFIX=$(pwd)/../install_ninja
  - cd ../build

script:
  - make
  - make test
  - make install
  - cd ../build_ninja
  - ../../ninja/ninja
  - ../../ninja.ninja test
  - ../../ninja.ninja install
